### ISSUE TITLE
My request to access mal-oss samples has gone unanswered for a long time

### ISSUE THREAD

**Issue by willTerner** [osssanitizer/maloss#16]
I already submitted request to access mal-oss samples last month. However, I have not received a reply so far. Could you please handle it as soon as possible. I need it as my train set for my research.
<img width="1391" alt="截屏2023-02-18 16 58 48" src="https://user-images.githubusercontent.com/75409032/219851768-b201aebf-550e-4108-9921-1171620b7e89.png">

**Comment by lingfennan** [comment]
invitation sent.
